/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-01-13 07:05:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.sql.*;
import java.util.*;

public final class facultyviewtimetable_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/connect.jsp", Long.valueOf(1640600254000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"keywords\" content=\"\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>Automation of Timetable Generation System</title>\r\n");
      out.write("<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    \r\n");
      out.write("    ");

    if (request.getParameter("msg") != null) {
      out.write("\r\n");
      out.write("    <script>alert('Login Success..!');</script>\r\n");
      out.write("    ");
}
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("    <div id=\"menu\">\r\n");
      out.write("    <ul>\r\n");
      out.write("    <li class=\"current_page_item\"><span><a href=\"index.html\">Home</a></span></li>\r\n");
      out.write("    <li><a href=\"admin.jsp\">Admin</a></li>\r\n");
      out.write("	<li><a href=\"student.jsp\">Student Login</a></li>\r\n");
      out.write("   <li><a href=\"facultyviewtimetable.jsp\">View Time Table</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- end #menu -->\r\n");
      out.write("    <div id=\"header\">\r\n");
      out.write("   \r\n");
      out.write("    <br/><center><p> <font size=\"6\" color=\"black\"><i><b> MIST  Timetable Generation </b></i></font></p></center>\r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"splash\">&nbsp;</div>\r\n");
      out.write("            <!-- end #header -->\r\n");
      out.write("    <div id=\"page\">\r\n");
      out.write("    <div id=\"page-bgtop\">\r\n");
      out.write("    <div id=\"page-bgbtm\">\r\n");
      out.write("    <div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("    <br/><br/>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");

	Connection connection = null;
 	try {
     	
	  	Class.forName("com.mysql.jdbc.Driver");	
		connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/timetable","root","");
      	String sql="";

	}
	catch(Exception e)
	{
		System.out.println(e);
	}

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");

    String query="select distinct yr from 1st "; 
    Statement st=connection.createStatement();
    ResultSet rs=st.executeQuery(query);
    
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <p align=\"justify\"><center>\r\n");
      out.write("    <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("    <font color=\"red\" size=\"5\">View Timetable</font></p>\r\n");
      out.write("    <form name=\"myform\" action=\"facultyviewtimetableact.jsp\" method=\"post\" id=\"\" >\r\n");
      out.write("    <table width=\"371\">\r\n");
      out.write("    \r\n");
      out.write("    <tr>\r\n");
      out.write("    <td height=\"43\"><font color=\"black\">Select Year</td>\r\n");
      out.write("    <td><select name=\"year\" style=\"width:170px;\" required=\"\">\r\n");
      out.write("    <option value=\"\" >Select</option>       \r\n");
      out.write("      ");
 

        while(rs.next())
        {

        String yr = rs.getString("yr");

       
      out.write("\r\n");
      out.write("       <option value=\"");
      out.print(yr);
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(yr);
      out.write("</option>\r\n");
      out.write("       ");
 }
      out.write("\r\n");
      out.write("       </select></td>\r\n");
      out.write("    </tr>    \r\n");
      out.write("    \r\n");
      out.write("    <tr>\r\n");
      out.write("    <td height=\"43\" rowspan=\"3\"></td>\r\n");
      out.write("    <td align=\"left\" valign=\"middle\">\r\n");
      out.write("    <p>\r\n");
      out.write("    <input name=\"submit\" type=\"submit\" value=\"VIEW\" />\r\n");
      out.write("    </p>\r\n");
      out.write("    <div align=\"right\">\r\n");
      out.write("    </div></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("    </form></center>\r\n");
      out.write("    </p>\r\n");
      out.write("    \r\n");
      out.write("    <br/><br/>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <div style=\"clear: both;\">&nbsp;</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"footer-wrapper\">\r\n");
      out.write("\r\n");
      out.write("    <div id=\"footer\">\r\n");
      out.write("    <p> Developed by: <a href=\"#\"><font color=\"white\">MIST</a>  </font></p>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
